# Generated by Django 5.1.2 on 2024-11-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
