# Generated by Django 5.1.2 on 2024-11-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_shopcontact_work_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcontact',
            name='instagram',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='shopcontact',
            name='twitter',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
