# Generated by Django 5.1.2 on 2024-11-11 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_shopcontact_instagram_shopcontact_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcontact',
            old_name='instagram',
            new_name='facebook',
        ),
    ]
