# Generated by Django 5.1.2 on 2024-11-28 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Currency code (e.g., USD, EUR)', max_length=3, unique=True)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., $, €)', max_length=5)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default currency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('main', 'Currency').objects.create(
                id=1,
                code='USD',
                symbol='$',
                is_default=True
            ),
            reverse_code=lambda apps, schema_editor: apps.get_model('main', 'Currency').objects.filter(id=1).delete()
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='main.currency'),
        ),
    ]
